repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: detect-private-key
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
            exclude: ^tests/.*/fixtures/.*
          - id: debug-statements
          # - id: detect-aws-credentials

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8

    - repo: https://github.com/ambv/black
      rev: 21.6b0
      hooks:
          - id: black

    # - repo: https://github.com/timothycrosley/isort
    #   rev: 5.8.0
    #   hooks:
    #       - id: isort
    #         additional_dependencies: [toml]
    #         exclude: ^.*/?setup\.py$
    # - repo: https://github.com/asottile/reorder_python_imports
    #   rev: v2.5.0
    #   hooks:
    #       - id: reorder-python-imports
    # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    #   rev: v1.0.5
    #   hooks:
    #       - id: python-bandit-vulnerability-check
    #         args: [-l, --recursive, -x, tests]
    #         files: .py$
